# -*- coding: utf-8 -*-
"""Copy of BCA_PSAT_W04_4.2_Exercises_Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n2oomknbJXqLxHOieGeEvLQGGTzSZ8SB

<br>
&nbsp; <img src="https://www.amrita.edu/ahead/images/aheadlogosticky.svg" alt="AMRITA AHEAD" width="250"> 
<table align="right">
  <td align="left"><a href="https://colab.research.google.com/drive/1jZQ2k4t_jO-DF4ekyHkLAelEe5KoDwzI">Prev: Strings in Python</a></td>
  <td align="right"><a href="https://colab.research.google.com/drive/1W3LjjmJj0kTjBUDx62PyUNFmJsMTjcfz">Next: String built-in functions</a></td>
</table>

# **Week 4 - Lab 4.2 - Simple Exercises on Strings**

For all the exercises mentioned below, write your program in the code segment just below the problem statement. Your program should print "YES" if the check succeeds (i.e. acceptable strings) and print "NO" otherwise.

1. Write a program that checks if the input string starts with char 'a'.<br>Accept a, amrita, ahead, algorithmic. Reject problem, solving, thinking.
"""

text = input()
if text[0] == 'a' :
  print('YES')
else :
  print('NO')

"""2. Write a program that checks if the input string starts and ends with the same char.<br>Accept amrita, xerox. Reject ahead, loop."""

s = input()
if s[0] == s[-1]:
  print("Yes")
else:
  print("No")

"""3. Write a program that checks if the input string does not end with the same char it starts with.<br>Accept ahead, loop. Reject amrita, xerox."""

s = input()
if s[0] == s[-1]:
  print("No")
else:
  print("Yes")

"""4. Write a program that checks if the input string contains at least one 'a'.<br>Accept amrita, ahead, algorithm, xyza. Reject problem, thinking."""

s = input()
n = s.count("a")
if n > 0:
  print("Yes")
else:
  print("No")

"""5. Write a program that checks if the input string contains exactly one a.<br>Accept algorithm, iteration. Reject amrita, ahead, problem."""

s = input()
n = s.count("a")
if n > 0:
  print("Yes")
else:
  print("No")

"""6. Write a program that checks if the input string contains two consecutive e's.<br>Accept engineer, evergreen. Reject amrita, ahead, center."""

s = input()
if "ee" in s:
  print("Yes")
else:
  print("No")

"""7. Write a program that checks if the input string does not contain two consecutive e's.<br>Accept amrita, ahead, center. Reject see, meet. """

s = input()
if "ee" in s:
  print("No")
else:
  print("Yes")

"""8. Write a program that checks if the input string contains at most two e's.<br>Accept amrita, ahead, center, green. Reject evergreen, ensemble."""

s = input()
if s.count("e") < 3:
  print("Yes")
else :
  print("No")

"""9. Write a program that checks if the input string contains two u's and three b's.<br>Accept ububb, bubblegum. Reject umbrella, bubble, gum"""

s = input()
if s.count("u") == 2 and s.count("b") == 3:
  print("Yes")
else :
  print("No")

"""10. Write a program that checks if the input string contains even number of e's.<br>Accept center, evergreen. Reject amrita, ahead, engineer."""

s = input()
if s.count("e") % 2 == 0:
  print("Yes")
else :
  print("No")

"""11. Write a program that checks if every e in the input string is followed by two s's.<br>Accept success, less, esspresso. Reject ahead, express."""

s = input()
for i in range(len(s) - 2):
  if s[i] == "e":
    if s[i + 1] == "s" and s[i + 2] == "s":
      pass
    else:
      print("No")
      break
else:
  print("Yes")

"""12. Write a program that checks if every e in the input string is preceded by two cc's.<br>Accept success. Reject excess."""

s = input()
for i in range(len(s) - 2):
  if s[i] == "c" and s[i+1] == "c":
    if s[i+2] == "e":
      pass
    else:
      print("No")
      break
else:
  print("Yes")

"""13. Write a program that checks if every a in the input string is preceded by two b's and followed by three c's.<br>Accept bbaccc, xbbacccyzbbaccc. Reject bxbaccc, bbacc, baccc."""

s = input()
for i in range(2,len(s) - 3):
  if s[i] == "a":
    if s[i - 2] == "b" and s[i - 1] == "b" and s[i + 1] == "c" and s[i + 2] == "c" and s[i + 3] == "c":
      pass
    else:
      print("No")
      break
else:
  print("Yes")

"""14. Write a program that checks if the input string of even length is a palindrome.<br>Accept amma, malayyalam. Reject ahead, malayalam."""

s = input()

for i in range(len(s)//2):
  if s[i] != s[-i -1]:
    print("No")
    break
else:
  print("Yes")

"""15. Write a program that checks if the input string is a palindrome.<br>Accept amma, malayalam, redivider. Reject ahead."""

s = input()

for i in range(len(s)//2):
  if s[i] != s[-i -1]:
    print("No")
    break
else:
  print("Yes")

"""
16. Write a program that counts and prints the number of vowels in the input string.<br>europe --> 4, amrita --> 3."""

s = input()
vowel = ["a","e","i","o","u"]
count = 0
for i in s:
  if i in vowel:
    count = count + 1
print(count)

"""17. Write a program that checks if the number of a's in the input string is equal to the number of b's.<br>Accept aaabbb, ababab, abcabcabc. Reject abacab, ahead."""

s = input()
if s.count("a") == s.count("b"):
  print("Yes")
else:
  print("No")

"""18. Write a program that checks (i) if the input string length is even, it should contain exactly two vowels (ii) if length is odd, it should contain odd number of vowels.<br>Accept team, tiktok, ahead. Reject amrita, online, graduate."""



s = input()
vowel = ["a","e","i","o","u"]

def count_vowel(string):
  vowel = ["a","e","i","o","u"]
  count = 0
  for i in string:
    if i in vowel:
      count = count + 1
  return count

if len(s) % 2 == 0:
  if count_vowel(s) == 2:
    print("Accepted in even ")
  else :
    print("Rejected in even")
else :
  if count_vowel(s) % 2 != 0:
    print("Accepted in odd")
  else :
    print("Rejected in odd")

"""19. Write a program that checks if two input strings are same.<br> Accept [amrita,amrita], [ahead,ahead]. Reject [amrita,ahead]."""

s1 = input()
s2 = input()
if s1 == s2:
  print("Yes")
else:
  print("No")

"""20. Write a program that checks if two input strings are anagrams.<br>Accept [trace,react], [dealer,leader]. Reject [amrita,ahead]"""

s1 = input()
s2 = input()
if len(s1) == len(s2):
  for i in s1:
    if i not in s2 :
      print("No")
      break
  else :
    print("Yes")
else :
  print("Nore")